/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExemploRouteImport } from './routes/exemplo'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r_.$slug'
import { Route as AuthenticatedMyPrivacyRouteImport } from './routes/_authenticated/my-privacy'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as RSlugRunRouteImport } from './routes/r_.$slug.run'
import { Route as AuthenticatedStudiesIdRouteImport } from './routes/_authenticated/studies.$id'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as AuthenticatedStudiesIdSynthesisRouteImport } from './routes/_authenticated/studies.$id.synthesis'
import { Route as AuthenticatedStudiesIdRespondentsRouteImport } from './routes/_authenticated/studies.$id.respondents'
import { Route as AuthenticatedStudiesIdInterviewsRouteImport } from './routes/_authenticated/studies.$id.interviews'
import { Route as AuthenticatedStudiesIdInterviewsUploadRouteImport } from './routes/_authenticated/studies.$id.interviews.upload'
import { Route as AuthenticatedStudiesIdInterviewsInterviewIdRouteImport } from './routes/_authenticated/studies.$id.interviews.$interviewId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemploRoute = ExemploRouteImport.update({
  id: '/exemplo',
  path: '/exemplo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r_/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyPrivacyRoute = AuthenticatedMyPrivacyRouteImport.update({
  id: '/my-privacy',
  path: '/my-privacy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const RSlugRunRoute = RSlugRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => RSlugRoute,
} as any)
const AuthenticatedStudiesIdRoute = AuthenticatedStudiesIdRouteImport.update({
  id: '/studies/$id',
  path: '/studies/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/admin/analytics',
    path: '/admin/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStudiesIdSynthesisRoute =
  AuthenticatedStudiesIdSynthesisRouteImport.update({
    id: '/synthesis',
    path: '/synthesis',
    getParentRoute: () => AuthenticatedStudiesIdRoute,
  } as any)
const AuthenticatedStudiesIdRespondentsRoute =
  AuthenticatedStudiesIdRespondentsRouteImport.update({
    id: '/respondents',
    path: '/respondents',
    getParentRoute: () => AuthenticatedStudiesIdRoute,
  } as any)
const AuthenticatedStudiesIdInterviewsRoute =
  AuthenticatedStudiesIdInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedStudiesIdRoute,
  } as any)
const AuthenticatedStudiesIdInterviewsUploadRoute =
  AuthenticatedStudiesIdInterviewsUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedStudiesIdInterviewsRoute,
  } as any)
const AuthenticatedStudiesIdInterviewsInterviewIdRoute =
  AuthenticatedStudiesIdInterviewsInterviewIdRouteImport.update({
    id: '/$interviewId',
    path: '/$interviewId',
    getParentRoute: () => AuthenticatedStudiesIdInterviewsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exemplo': typeof ExemploRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-privacy': typeof AuthenticatedMyPrivacyRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/studies/$id': typeof AuthenticatedStudiesIdRouteWithChildren
  '/r/$slug/run': typeof RSlugRunRoute
  '/studies/$id/interviews': typeof AuthenticatedStudiesIdInterviewsRouteWithChildren
  '/studies/$id/respondents': typeof AuthenticatedStudiesIdRespondentsRoute
  '/studies/$id/synthesis': typeof AuthenticatedStudiesIdSynthesisRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/studies/$id/interviews/$interviewId': typeof AuthenticatedStudiesIdInterviewsInterviewIdRoute
  '/studies/$id/interviews/upload': typeof AuthenticatedStudiesIdInterviewsUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exemplo': typeof ExemploRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-privacy': typeof AuthenticatedMyPrivacyRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/studies/$id': typeof AuthenticatedStudiesIdRouteWithChildren
  '/r/$slug/run': typeof RSlugRunRoute
  '/studies/$id/interviews': typeof AuthenticatedStudiesIdInterviewsRouteWithChildren
  '/studies/$id/respondents': typeof AuthenticatedStudiesIdRespondentsRoute
  '/studies/$id/synthesis': typeof AuthenticatedStudiesIdSynthesisRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/studies/$id/interviews/$interviewId': typeof AuthenticatedStudiesIdInterviewsInterviewIdRoute
  '/studies/$id/interviews/upload': typeof AuthenticatedStudiesIdInterviewsUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/exemplo': typeof ExemploRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-privacy': typeof AuthenticatedMyPrivacyRoute
  '/r_/$slug': typeof RSlugRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/studies/$id': typeof AuthenticatedStudiesIdRouteWithChildren
  '/r_/$slug/run': typeof RSlugRunRoute
  '/_authenticated/studies/$id/interviews': typeof AuthenticatedStudiesIdInterviewsRouteWithChildren
  '/_authenticated/studies/$id/respondents': typeof AuthenticatedStudiesIdRespondentsRoute
  '/_authenticated/studies/$id/synthesis': typeof AuthenticatedStudiesIdSynthesisRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/_authenticated/studies/$id/interviews/$interviewId': typeof AuthenticatedStudiesIdInterviewsInterviewIdRoute
  '/_authenticated/studies/$id/interviews/upload': typeof AuthenticatedStudiesIdInterviewsUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exemplo'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/my-privacy'
    | '/r/$slug'
    | '/admin/analytics'
    | '/studies/$id'
    | '/r/$slug/run'
    | '/studies/$id/interviews'
    | '/studies/$id/respondents'
    | '/studies/$id/synthesis'
    | '/api/public/telegram/webhook'
    | '/studies/$id/interviews/$interviewId'
    | '/studies/$id/interviews/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exemplo'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/my-privacy'
    | '/r/$slug'
    | '/admin/analytics'
    | '/studies/$id'
    | '/r/$slug/run'
    | '/studies/$id/interviews'
    | '/studies/$id/respondents'
    | '/studies/$id/synthesis'
    | '/api/public/telegram/webhook'
    | '/studies/$id/interviews/$interviewId'
    | '/studies/$id/interviews/upload'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/exemplo'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-privacy'
    | '/r_/$slug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/studies/$id'
    | '/r_/$slug/run'
    | '/_authenticated/studies/$id/interviews'
    | '/_authenticated/studies/$id/respondents'
    | '/_authenticated/studies/$id/synthesis'
    | '/api/public/telegram/webhook'
    | '/_authenticated/studies/$id/interviews/$interviewId'
    | '/_authenticated/studies/$id/interviews/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ExemploRoute: typeof ExemploRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  RSlugRoute: typeof RSlugRouteWithChildren
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplo': {
      id: '/exemplo'
      path: '/exemplo'
      fullPath: '/exemplo'
      preLoaderRoute: typeof ExemploRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r_/$slug': {
      id: '/r_/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-privacy': {
      id: '/_authenticated/my-privacy'
      path: '/my-privacy'
      fullPath: '/my-privacy'
      preLoaderRoute: typeof AuthenticatedMyPrivacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/r_/$slug/run': {
      id: '/r_/$slug/run'
      path: '/run'
      fullPath: '/r/$slug/run'
      preLoaderRoute: typeof RSlugRunRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/_authenticated/studies/$id': {
      id: '/_authenticated/studies/$id'
      path: '/studies/$id'
      fullPath: '/studies/$id'
      preLoaderRoute: typeof AuthenticatedStudiesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studies/$id/synthesis': {
      id: '/_authenticated/studies/$id/synthesis'
      path: '/synthesis'
      fullPath: '/studies/$id/synthesis'
      preLoaderRoute: typeof AuthenticatedStudiesIdSynthesisRouteImport
      parentRoute: typeof AuthenticatedStudiesIdRoute
    }
    '/_authenticated/studies/$id/respondents': {
      id: '/_authenticated/studies/$id/respondents'
      path: '/respondents'
      fullPath: '/studies/$id/respondents'
      preLoaderRoute: typeof AuthenticatedStudiesIdRespondentsRouteImport
      parentRoute: typeof AuthenticatedStudiesIdRoute
    }
    '/_authenticated/studies/$id/interviews': {
      id: '/_authenticated/studies/$id/interviews'
      path: '/interviews'
      fullPath: '/studies/$id/interviews'
      preLoaderRoute: typeof AuthenticatedStudiesIdInterviewsRouteImport
      parentRoute: typeof AuthenticatedStudiesIdRoute
    }
    '/_authenticated/studies/$id/interviews/upload': {
      id: '/_authenticated/studies/$id/interviews/upload'
      path: '/upload'
      fullPath: '/studies/$id/interviews/upload'
      preLoaderRoute: typeof AuthenticatedStudiesIdInterviewsUploadRouteImport
      parentRoute: typeof AuthenticatedStudiesIdInterviewsRoute
    }
    '/_authenticated/studies/$id/interviews/$interviewId': {
      id: '/_authenticated/studies/$id/interviews/$interviewId'
      path: '/$interviewId'
      fullPath: '/studies/$id/interviews/$interviewId'
      preLoaderRoute: typeof AuthenticatedStudiesIdInterviewsInterviewIdRouteImport
      parentRoute: typeof AuthenticatedStudiesIdInterviewsRoute
    }
  }
}

interface AuthenticatedStudiesIdInterviewsRouteChildren {
  AuthenticatedStudiesIdInterviewsInterviewIdRoute: typeof AuthenticatedStudiesIdInterviewsInterviewIdRoute
  AuthenticatedStudiesIdInterviewsUploadRoute: typeof AuthenticatedStudiesIdInterviewsUploadRoute
}

const AuthenticatedStudiesIdInterviewsRouteChildren: AuthenticatedStudiesIdInterviewsRouteChildren =
  {
    AuthenticatedStudiesIdInterviewsInterviewIdRoute:
      AuthenticatedStudiesIdInterviewsInterviewIdRoute,
    AuthenticatedStudiesIdInterviewsUploadRoute:
      AuthenticatedStudiesIdInterviewsUploadRoute,
  }

const AuthenticatedStudiesIdInterviewsRouteWithChildren =
  AuthenticatedStudiesIdInterviewsRoute._addFileChildren(
    AuthenticatedStudiesIdInterviewsRouteChildren,
  )

interface AuthenticatedStudiesIdRouteChildren {
  AuthenticatedStudiesIdInterviewsRoute: typeof AuthenticatedStudiesIdInterviewsRouteWithChildren
  AuthenticatedStudiesIdRespondentsRoute: typeof AuthenticatedStudiesIdRespondentsRoute
  AuthenticatedStudiesIdSynthesisRoute: typeof AuthenticatedStudiesIdSynthesisRoute
}

const AuthenticatedStudiesIdRouteChildren: AuthenticatedStudiesIdRouteChildren =
  {
    AuthenticatedStudiesIdInterviewsRoute:
      AuthenticatedStudiesIdInterviewsRouteWithChildren,
    AuthenticatedStudiesIdRespondentsRoute:
      AuthenticatedStudiesIdRespondentsRoute,
    AuthenticatedStudiesIdSynthesisRoute: AuthenticatedStudiesIdSynthesisRoute,
  }

const AuthenticatedStudiesIdRouteWithChildren =
  AuthenticatedStudiesIdRoute._addFileChildren(
    AuthenticatedStudiesIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyPrivacyRoute: typeof AuthenticatedMyPrivacyRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedStudiesIdRoute: typeof AuthenticatedStudiesIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyPrivacyRoute: AuthenticatedMyPrivacyRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedStudiesIdRoute: AuthenticatedStudiesIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface RSlugRouteChildren {
  RSlugRunRoute: typeof RSlugRunRoute
}

const RSlugRouteChildren: RSlugRouteChildren = {
  RSlugRunRoute: RSlugRunRoute,
}

const RSlugRouteWithChildren = RSlugRoute._addFileChildren(RSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ExemploRoute: ExemploRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  RSlugRoute: RSlugRouteWithChildren,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
